# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-13 19:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailforms', '0003_capitalizeverbose'),
        ('wagtailcore', '0030_index_on_pagerevision_created_at'),
        ('wagtailredirects', '0005_capitalizeverbose'),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authorsnippet',
            name='portrait',
        ),
        migrations.RemoveField(
            model_name='authorsnippet',
            name='user',
        ),
        migrations.RemoveField(
            model_name='subjectcategorypage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='subjectindexpage',
            name='page_ptr',
        ),
        migrations.DeleteModel(
            name='AuthorSnippet',
        ),
        migrations.DeleteModel(
            name='SubjectCategoryPage',
        ),
        migrations.DeleteModel(
            name='SubjectIndexPage',
        ),
    ]
