# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-13 19:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20161213_1921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlesourcelink',
            name='page',
        ),
        migrations.DeleteModel(
            name='ArticleSourceLink',
        ),
    ]
