# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-22 20:53
from __future__ import unicode_literals

from django.db import migrations, models
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtailembeds.blocks
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20161214_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleindexpage',
            name='intro',
            field=models.TextField(blank=True, help_text='This text will be formatted with markdown.'),
        ),
        migrations.AlterField(
            model_name='articleindexrelatedlink',
            name='link_external',
            field=models.URLField(blank=True, verbose_name='External link'),
        ),
        migrations.AlterField(
            model_name='articleindexrelatedlink',
            name='title',
            field=models.CharField(help_text='Link title', max_length=255),
        ),
        migrations.AlterField(
            model_name='articlepage',
            name='body',
            field=wagtail.wagtailcore.fields.StreamField((('text', wagtail.wagtailcore.blocks.TextBlock(help_text='This text will be formatted with markdown.', icon='pilcrow')), ('image', wagtail.wagtailcore.blocks.StructBlock((('image', wagtail.wagtailimages.blocks.ImageChooserBlock()), ('caption', wagtail.wagtailcore.blocks.CharBlock(blank=True, help_text='This will override the default caption.This text will be formatted with markdown.', null=True, required=False))))), ('embed', wagtail.wagtailembeds.blocks.EmbedBlock(icon='media')), ('pull_quote', wagtail.wagtailcore.blocks.StructBlock((('quote', wagtail.wagtailcore.blocks.TextBlock()), ('author', wagtail.wagtailcore.blocks.CharBlock())))))),
        ),
        migrations.AlterField(
            model_name='articlepage',
            name='date',
            field=models.DateField(verbose_name='Post date'),
        ),
        migrations.AlterField(
            model_name='articlepage',
            name='intro',
            field=models.TextField(help_text='This will only appear in article previews, not with the full article.This text will be formatted with markdown.', max_length=250),
        ),
        migrations.AlterField(
            model_name='authorindexpage',
            name='intro',
            field=models.TextField(blank=True, help_text='This text will be formatted with markdown.'),
        ),
        migrations.AlterField(
            model_name='authorpage',
            name='long_bio',
            field=models.TextField(blank=True, help_text='This text will appear on the author page.This text will be formatted with markdown.', null=True),
        ),
        migrations.AlterField(
            model_name='authorpage',
            name='short_bio',
            field=models.TextField(blank=True, help_text='This text will appear at the end of articles.This text will be formatted with markdown.', max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='subjectpage',
            name='description',
            field=models.TextField(blank=True, help_text='This text will be formatted with markdown.', max_length=800, null=True),
        ),
    ]
