# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-02-26 19:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20180226_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepage',
            name='main_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.CustomImage'),
        ),
    ]
