# Generated by Django 2.0.5 on 2018-07-22 18:07

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('blog', '0023_auto_20180613_0219'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudienceIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
            ],
            options={
                'verbose_name': 'Audiences',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='AudienceLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AudiencePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('intro', models.TextField(max_length=480)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.RemoveField(
            model_name='articleindexrelatedlink',
            name='link_page',
        ),
        migrations.RemoveField(
            model_name='articleindexrelatedlink',
            name='page',
        ),
        migrations.RemoveField(
            model_name='articleindexpage',
            name='intro',
        ),
        migrations.AddField(
            model_name='articlepage',
            name='notes',
            field=models.TextField(blank=True, help_text='This text will not appear on the page.', null=True),
        ),
        migrations.DeleteModel(
            name='ArticleIndexRelatedLink',
        ),
        migrations.AddField(
            model_name='audiencelink',
            name='audience',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.AudiencePage'),
        ),
        migrations.AddField(
            model_name='audiencelink',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_audiences', to='blog.ArticlePage'),
        ),
    ]
