# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-26 20:43
from __future__ import unicode_literals

from django.db import migrations

from wagtail.wagtailimages.utils import get_fill_filter_spec_migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    forward, reverse = get_fill_filter_spec_migrations('images', 'CustomRendition')

    operations = [
        migrations.AlterUniqueTogether(
            name='customrendition',
            unique_together=set([('image', 'filter_spec', 'focal_point_key')]),
        ),
        migrations.RunPython(forward, reverse),

    ]
