# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-26 20:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_auto_20180226_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customrendition',
            name='filter_spec',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
