# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-26 20:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_auto_20180226_2056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customrendition',
            name='filter',
        ),
        migrations.AlterField(
            model_name='customrendition',
            name='focal_point_key',
            field=models.CharField(blank=True, default='', editable=False, max_length=16),
        ),
    ]
