# Generated by Django 2.0.5 on 2018-06-01 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0004_auto_20180226_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customrendition',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renditions', to='images.CustomImage'),
        ),
    ]
