# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-13 17:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0030_index_on_pagerevision_created_at'),
        ('wagtailimages', '0015_fill_filter_spec_field'),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(help_text='Website name', max_length=127)),
                ('site_tagline', models.CharField(blank=True, help_text='Tagline to show after the site title', max_length=255)),
                ('site_description', models.TextField(blank=True, help_text='Description of website (to appear on searches)')),
                ('pagination_count', models.PositiveIntegerField(default=10, help_text='Number of posts to display per page on index pages')),
                ('disqus', models.CharField(blank=True, help_text='Site name on Disqus. Comments will only appear if this is provided.', max_length=127, null=True)),
                ('google_analytics_id', models.CharField(blank=True, help_text='Google Analytics Tracking ID', max_length=127, null=True)),
                ('google_custom_search_key', models.CharField(blank=True, help_text='Unique ID for Google Custom Search', max_length=127, null=True)),
                ('favicon', models.ForeignKey(blank=True, help_text='Icon for site in browsers (Must be .ico file to work)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.Site')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
