# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-13 19:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_infopage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='infopage',
            options={'verbose_name': 'Information Page'},
        ),
    ]
