# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-22 20:53
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtailembeds.blocks
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20161213_1907'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generalsettings',
            name='favicon',
        ),
        migrations.AlterField(
            model_name='infopage',
            name='body',
            field=wagtail.wagtailcore.fields.StreamField((('text', wagtail.wagtailcore.blocks.TextBlock(help_text='This text will be formatted with markdown.', icon='pilcrow')), ('image', wagtail.wagtailcore.blocks.StructBlock((('image', wagtail.wagtailimages.blocks.ImageChooserBlock()), ('caption', wagtail.wagtailcore.blocks.CharBlock(blank=True, help_text='This will override the default caption.This text will be formatted with markdown.', null=True, required=False))))), ('embed', wagtail.wagtailembeds.blocks.EmbedBlock(icon='media')))),
        ),
    ]
