# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-31 05:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('home', '0006_auto_20161222_2053'),
    ]

    operations = [
        migrations.CreateModel(
            name='StyleSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title_font', models.CharField(help_text='Name of font family to use for site title', max_length=127)),
                ('site_title_weight', models.CharField(help_text='eg, bold, 700', max_length=127)),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.Site')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
