# Generated by Django 2.0.5 on 2018-06-01 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_stylesettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='previewarticle',
            name='article',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.ArticlePage'),
        ),
    ]
