# Generated by Django 2.0.5 on 2018-06-01 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20180601_0454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stylesettings',
            name='site_title_font',
            field=models.CharField(blank=True, help_text='Name of font family to use for site title', max_length=127, null=True),
        ),
        migrations.AlterField(
            model_name='stylesettings',
            name='site_title_weight',
            field=models.CharField(blank=True, help_text='eg, bold, 700', max_length=127, null=True),
        ),
    ]
