# Generated by Django 2.0.5 on 2018-06-04 01:26

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.embeds.blocks
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20180601_0511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infopage',
            name='body',
            field=wagtail.core.fields.StreamField([('text', wagtail.core.blocks.TextBlock(help_text='This text will be formatted with markdown.', icon='pilcrow')), ('image', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('caption', wagtail.core.blocks.CharBlock(blank=True, help_text='This will override the default caption.This text will be formatted with markdown.', null=True, required=False)), ('format', wagtail.core.blocks.CharBlock(choices=[('full', 'Full width'), ('medium', 'Medium centered'), ('left', 'Left-aligned'), 'rightRight-aligned']))])), ('embed', wagtail.embeds.blocks.EmbedBlock(icon='media'))]),
        ),
    ]
