# Generated by Django 2.0.5 on 2018-06-15 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_remove_generalsettings_site_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generalsettings',
            name='google_custom_search_key',
        ),
    ]
