# Generated by Django 2.0.5 on 2018-06-19 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_auto_20180619_0416'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generalsettings',
            name='site_description',
        ),
        migrations.RemoveField(
            model_name='generalsettings',
            name='site_tagline',
        ),
        migrations.AddField(
            model_name='generalsettings',
            name='site_author',
            field=models.TextField(blank=True, max_length=127, null=True),
        ),
        migrations.AddField(
            model_name='generalsettings',
            name='site_author_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
